// Code generated by goctl. DO NOT EDIT.
// Source: test.proto

package server

import (
	"context"

	"protoc/internal/logic"
	"protoc/internal/svc"
	"protoc/pb/test"
)

type TestServer struct {
	svcCtx *svc.ServiceContext
	test.UnimplementedTestServer
}

func NewTestServer(svcCtx *svc.ServiceContext) *TestServer {
	return &TestServer{
		svcCtx: svcCtx,
	}
}

func (s *TestServer) Ping(ctx context.Context, in *test.Request) (*test.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
