// Code generated by goctl. DO NOT EDIT.
// Source: test.proto

package testclient

import (
	"context"

	"protoc/pb/test"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = test.Request
	Response = test.Response

	Test interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultTest struct {
		cli zrpc.Client
	}
)

func NewTest(cli zrpc.Client) Test {
	return &defaultTest{
		cli: cli,
	}
}

func (m *defaultTest) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := test.NewTestClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
